# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QAbstractSpinBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 10, 761, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.DataGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.DataGrid.setContentsMargins(0, 0, 0, 0)
        self.DataGrid.setObjectName("DataGrid")
        self.numberOfVariablesLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.numberOfVariablesLabel.setFont(font)
        self.numberOfVariablesLabel.setObjectName("numberOfVariablesLabel")
        self.DataGrid.addWidget(self.numberOfVariablesLabel, 0, 0, 1, 1)
        self.methodLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.methodLabel.setFont(font)
        self.methodLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.methodLabel.setObjectName("methodLabel")
        self.DataGrid.addWidget(self.methodLabel, 0, 2, 1, 1)
        self.numberOfVariables = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.numberOfVariables.setMinimum(1)
        self.numberOfVariables.setMaximum(10)
        self.numberOfVariables.setObjectName("numberOfVariables")
        self.DataGrid.addWidget(self.numberOfVariables, 0, 1, 1, 1)
        self.Method = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.Method.setObjectName("Method")
        self.Method.addItem("")
        self.Method.addItem("")
        self.Method.addItem("")
        self.Method.addItem("")
        self.DataGrid.addWidget(self.Method, 0, 3, 1, 1)
        self.maximizeRadio = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.maximizeRadio.setFont(font)
        self.maximizeRadio.setChecked(True)
        self.maximizeRadio.setObjectName("maximizeRadio")
        self.DataGrid.addWidget(self.maximizeRadio, 1, 3, 1, 1)
        self.numberOfConstrainsLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.numberOfConstrainsLabel.setFont(font)
        self.numberOfConstrainsLabel.setObjectName("numberOfConstrainsLabel")
        self.DataGrid.addWidget(self.numberOfConstrainsLabel, 1, 0, 1, 1)
        self.numberOfConstraints = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.numberOfConstraints.setMinimum(1)
        self.numberOfConstraints.setMaximum(10)
        self.numberOfConstraints.setObjectName("numbeOfConstraints")
        self.DataGrid.addWidget(self.numberOfConstraints, 1, 1, 1, 1)
        self.objectiveFunctionLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.objectiveFunctionLabel.setGeometry(QtCore.QRect(40, 160, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.objectiveFunctionLabel.setFont(font)
        self.objectiveFunctionLabel.setObjectName("objectiveFunctionLabel")
        self.constainsLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.constainsLabel.setGeometry(QtCore.QRect(40, 220, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.constainsLabel.setFont(font)
        self.constainsLabel.setObjectName("constainsLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        ###########################################################################
        self.objective =[]
        self.objectiveLabels =[]
        for i in range(0,10):
            x = QtWidgets.QSpinBox(parent=self.centralwidget)

            x.setObjectName("objective" + str(i))
            x.setGeometry(QtCore.QRect(40 + 100*i, 190, 0, 20))
            x.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
            l = QtWidgets.QLabel(parent=self.centralwidget)
            l.setText('x' + str(i + 1) +' +')
            x.setMaximumWidth(60)
            l.setFont(font)
            l.setGeometry(QtCore.QRect(100 + 100 * i, 190, 40, 20))
            self.objective.append(x)
            self.objectiveLabels.append(l)

        self.constraints = []
        self.constraintsLabels = []
        self.constraintSigns = []
        self.constrainValues= []
        for i in range(0,10):
            const = []
            labels =[]
            for j in range(0,10):
                x = QtWidgets.QSpinBox(parent=self.centralwidget)
                x.setObjectName("constraint" + str(j))
                x.setGeometry(QtCore.QRect(40 + 100 * j, 400+ 40*i, 0, 20))
                x.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)

                l = QtWidgets.QLabel(parent=self.centralwidget)
                l.setText('x' + str(j + 1) + ' +')
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(12)
                x.setMaximumWidth(60)
                l.setFont(font)
                l.setGeometry(QtCore.QRect(100 + 100 * j, 400+40*i, 40, 20))
                labels.append(l)
                const.append(x)
            self.constraints.append(const)
            self.constraintsLabels.append(labels)

            q = QtWidgets.QComboBox(parent=self.centralwidget)
            q.setObjectName("constraint sign" + str(i))
            q.addItem("≤")
            q.addItem("≥")
            q.addItem("=")
            q.setGeometry(QtCore.QRect(1050, 400+40*i, 40, 20))
            q.setFont(font)
            self.constraintSigns.append(q)

            ans = QtWidgets.QSpinBox(parent=self.centralwidget)
            ans.setObjectName("ans sign" + str(i))
            ans.setGeometry(QtCore.QRect(1100, 400+40*i, 40, 20))
            ans.setFont(font)
            self.constrainValues.append(ans)

        self.typeLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.typeLabel.setObjectName("typeLabel")
        self.typeLabel.setFont(font)
        self.typeLabel.setGeometry(QtCore.QRect(1250, 220, 200, 20))
        self.typeLabel.setText("Decision Variables Types: ")

        self.types = []
        self.typeLabels = []
        for i in range(0,10):
            q = QtWidgets.QComboBox(parent=self.centralwidget)
            q.setObjectName("type" + str(i))
            q.addItem('≥ 0')
            q.addItem("URV")
            q.setFont(font)
            q.setGeometry(QtCore.QRect(1340, 260 + 40*i, 70, 20))
            l = QtWidgets.QLabel(parent=self.centralwidget)
            l.setText('x' + str(i) )
            l.setFont(font)
            l.setGeometry(QtCore.QRect(1300, 260 + 40*i, 40, 20))
            self.types.append(q)
            self.typeLabels.append(l)

        ###########################################################################

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.numberOfVariablesLabel.setText(_translate("MainWindow", "Number of decision variables:"))
        self.methodLabel.setText(_translate("MainWindow", "                                    Method:"))
        self.Method.setItemText(0, _translate("MainWindow", "Simple Simplex"))
        self.Method.setItemText(1, _translate("MainWindow", "Big M Method"))
        self.Method.setItemText(2, _translate("MainWindow", "2 Phase Method"))
        self.Method.setItemText(3, _translate("MainWindow", "Preemtive Goal Programming"))
        self.maximizeRadio.setText(_translate("MainWindow", "Maximize ?"))
        self.numberOfConstrainsLabel.setText(_translate("MainWindow", "Number of constraints:"))
        self.objectiveFunctionLabel.setText(_translate("MainWindow", "Objective function :"))
        self.constainsLabel.setText(_translate("MainWindow", "Constrains:"))
